/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atenas.frames;

import algoritimos.annotations.MapFrameField;
import algoritimos.beans.JTextFieldCBI;
import algoritimos.paineis.MenuBarCbiDefault;
import br.com.atenas.listeners.Cad_ClienteListener;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Tiago
 */
public class Cad_ClienteFrame extends javax.swing.JFrame {

    private final Cad_ClienteListener listener;

    /**
     * Creates new form Cad_ClienteFrame
     */
    public Cad_ClienteFrame() {
        initComponents();
        listener = new Cad_ClienteListener(this);
    }

    public MenuBarCbiDefault getMenuBarCbiDefault() {
        return menuBarCbiDefault;
    }

    public JPanel getPainelMain() {
        return painelMain;
    }

    @MapFrameField(referenceField = "documento", typeReference = String.class)
    public JTextFieldCBI getTxtDocumento() {
        return txtDocumento;
    }

    @MapFrameField(referenceField = "id", typeReference = Long.class)
    public JTextField getTxtId() {
        return txtId;
    }

    @MapFrameField(referenceField = "nome", typeReference = String.class)
    public JTextFieldCBI getTxtNome() {
        return txtNome;
    }

    @MapFrameField(referenceField = "telefones", typeReference = List.class)
    public JTable getTbTelefones() {
        return painel_Telefones.getTbDados();
    }

    @MapFrameField(referenceField = "email", typeReference = List.class)
    public JTable getTbEmails() {
        return painel_Emails.getTbDados();
    }

    @MapFrameField(referenceField = "carros", typeReference = List.class)
    public JTable getTbCarros(){
        return painel_Carros.getTbDados();
    }
    
    public Painel_Cad_Geral getPainel_Emails() {
        return painel_Emails;
    }

    public Painel_Cad_Geral getPainel_Telefones() {
        return painel_Telefones;
    }

    public Painel_Cad_Geral getPainel_Carros() {
        return painel_Carros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scMain = new javax.swing.JScrollPane();
        painelMain = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbDocumento = new javax.swing.JLabel();
        txtDocumento = new algoritimos.beans.JTextFieldCBI();
        lbNome = new javax.swing.JLabel();
        txtNome = new algoritimos.beans.JTextFieldCBI();
        tbGuias = new javax.swing.JTabbedPane();
        painel_Telefones = new br.com.atenas.frames.Painel_Cad_Geral();
        painel_Emails = new br.com.atenas.frames.Painel_Cad_Geral();
        painel_Carros = new br.com.atenas.frames.Painel_Cad_Geral();
        menuBarCbiDefault = new algoritimos.paineis.MenuBarCbiDefault();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        lbId.setText("Id");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        lbDocumento.setText("Documento");

        txtDocumento.setEnabled(false);
        txtDocumento.setMaxLength(50);

        lbNome.setText("Nome");

        txtNome.setEnabled(false);
        txtNome.setMaxLength(255);

        tbGuias.addTab("Telefones", painel_Telefones);
        tbGuias.addTab("E-mails", painel_Emails);
        tbGuias.addTab("Carros", painel_Carros);

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelMainLayout.createSequentialGroup()
                        .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(tbGuias, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbGuias))
        );

        scMain.setViewportView(painelMain);

        setJMenuBar(menuBarCbiDefault);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scMain, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_ClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDocumento;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNome;
    private algoritimos.paineis.MenuBarCbiDefault menuBarCbiDefault;
    private javax.swing.JPanel painelMain;
    private br.com.atenas.frames.Painel_Cad_Geral painel_Carros;
    private br.com.atenas.frames.Painel_Cad_Geral painel_Emails;
    private br.com.atenas.frames.Painel_Cad_Geral painel_Telefones;
    private javax.swing.JScrollPane scMain;
    private javax.swing.JTabbedPane tbGuias;
    private algoritimos.beans.JTextFieldCBI txtDocumento;
    private javax.swing.JTextField txtId;
    private algoritimos.beans.JTextFieldCBI txtNome;
    // End of variables declaration//GEN-END:variables
}
