CREATE SEQUENCE ROOT.CARRO_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE ROOT.ENT_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE ROOT.EMAIL_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE ROOT.NOTA_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE ROOT.TEL_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;
CREATE SEQUENCE ROOT.ITEM_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CYCLE;